# Generated by Django 5.1.2 on 2024-10-23 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_jobmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobmodel',
            name='posted_date',
        ),
        migrations.RemoveField(
            model_name='jobmodel',
            name='update_date',
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='job_Pic',
            field=models.ImageField(null=True, upload_to='Media/job_Pic'),
        ),
    ]
